/* ==========================================================
   劇本資料 · 單一資料來源（Single Source of Truth）
   新增 / 修改劇本只需改這裡一處。
   index.html 與 榮譽牆.html 皆讀取 window.SCRIPTS。
   欄位：id 名稱 file 路徑 / players 人數(數字,篩選用)
        playersLabel 人數顯示 / time 時長(數字,排序用) timeLabel 顯示
        difficulty 難度 0-5 / types 標籤 / theme 主題色
        poster 海報URL / reviewKey 榮譽牆評價對應鍵(CSV「劇本」欄)
        characters 角色名單（新增玩本記錄表單的角色下拉選項）
   ========================================================== */
window.SCRIPTS = [
  {"id":"wangzuo","name":"王座","file":"7人/王座.html","players":7,"playersLabel":"4男3女","time":4.5,"timeLabel":"4.5小時","difficulty":2,"types":["神話","陣營","機制","新手","身份轉換"],"theme":"mytho","poster":"https://i.postimg.cc/d0cKpGxL/2021-11-13-195627.jpg","reviewKey":"王座","characters":["巨狼芬里爾","守護神海姆達爾","神后弗麗嘉","雷神托爾","詭計之神洛基","女武神瓦基里","青春女神希芙"]},
  {"id":"beiguo","name":"北國之春","file":"6人/北國之春.html","players":6,"playersLabel":"3男3女","time":4,"timeLabel":"4小時","difficulty":3,"types":["歡樂","推理","新手","情感"],"theme":"history","poster":"https://i.postimg.cc/yNWMsNFR/01.jpg","reviewKey":"北國之春","characters":["娜塔莉","維克多","尤里希","索菲亞","康斯坦丁","鮑里斯"]},
  {"id":"bielai","name":"別來無恙","file":"6人/別來無恙.html","players":6,"playersLabel":"3男3女","time":4,"timeLabel":"4小時","difficulty":1,"types":["情感","現代","新手","愛情","校園","遺憾"],"theme":"love","poster":"https://i.postimg.cc/ZR8GbTTx/image.jpg","reviewKey":"別來無恙","characters":["夏藍","顧夢嬌","梁白","陳久然","李斯哲","簡珩"]},
  {"id":"fengtian","name":"奉天1928","file":"5人/奉天1928.html","players":5,"playersLabel":"3男2女","time":4,"timeLabel":"4小時","difficulty":3,"types":["情感","民國","軍閥","家國","沉浸"],"theme":"history","poster":"https://i.postimg.cc/W3Z7nM68/image.jpg","reviewKey":"奉天1928","characters":["董制夷","董晴","魏聞聲","馮昊","赫連珊"]},
  {"id":"gucheng","name":"孤城","file":"7人/孤城.html","players":7,"playersLabel":"4男3女","time":4.5,"timeLabel":"4.5小時","difficulty":2,"types":["陣營","機制","情感","民國","諜戰"],"theme":"desert","poster":"https://i.postimg.cc/cCsdmcGG/b644a7b3-c9a4-4d08-b36d-c69cc70a0b39-S.png","reviewKey":"孤城","characters":["陳懷安","樓小蘭","柳湘人","鐵男","蔣古城","麗麗娜依","夜神"]},
  {"id":"bingjiao","name":"病嬌男孩的精分日記","file":"7人/病嬌男孩的精分日記.html","players":7,"playersLabel":"7人不限","time":4.5,"timeLabel":"4-5小時","difficulty":4,"types":["微恐","還原","推理","沉浸"],"theme":"horror","poster":"https://i.postimg.cc/RZYbc6pZ/1.jpg","reviewKey":"病嬌男孩的精分日記","characters":["蕭何"]},
  {"id":"yinyuan","name":"陰緣","file":"6人/陰緣.html","players":6,"playersLabel":"3男3女","time":4,"timeLabel":"4小時","difficulty":2,"types":["古風","情感","恐怖","沉浸","雙主持"],"theme":"ancient","poster":"https://i.postimg.cc/qqp3BtDL/image.jpg","reviewKey":"陰緣","characters":["李天青","李康節","程遠常","程小宛","海棠","夏雲煙"]},
  {"id":"qingtian","name":"晴天神社","file":"6人/晴天神社.html","players":6,"playersLabel":"4男2女","time":4,"timeLabel":"4小時","difficulty":0,"types":["情感","日式","沉浸","還原","無兇手","新手"],"theme":"shrine","poster":"https://i.postimg.cc/QMd81msL/image.png","reviewKey":"晴天神社","characters":["木村聖也","清水琉奈","秋元英樹","長澤龍之介","小野光夫","木村一郎"]},
  {"id":"lichuan","name":"漓川怪談簿","file":"7人/漓川怪談簿.html","players":7,"playersLabel":"3男4女","time":4.5,"timeLabel":"4.5小時","difficulty":4,"types":["日式","硬核推理","精怪","密室","進階","還原"],"theme":"mystery","poster":"https://i.postimg.cc/KvyQtdnC/海報.jpg","reviewKey":"漓川怪談簿","characters":["青衣女子","紅衣女子","黑衣少年","衣衫襤褸的老人","白衣少女","繃帶怪人","小女孩"]},
  {"id":"nairao","name":"誰動了我的奶酪","file":"6人/誰動了我的奶酪.html","players":6,"playersLabel":"2男4女","time":4,"timeLabel":"4小時","difficulty":3,"types":["歡樂","新手","童話","推理","輕鬆"],"theme":"happy","poster":"https://i.postimg.cc/hjP711CF/image.jpg","reviewKey":"誰動了我的奶酪","characters":["黑髮少女","小男孩","啞巴姑娘","金髮少女","小女孩","鬍子叔叔"]},
  {"id":"kuaile","name":"賣快樂的人","file":"5人/賣快樂的人.html","players":5,"playersLabel":"2男3女","time":5,"timeLabel":"5小時","difficulty":1,"types":["情感","新手","沉浸","立意","日式","現代","無兇手"],"theme":"modern","poster":"https://i.postimg.cc/8zDnCPgc/image.jpg","reviewKey":"賣快樂的人","characters":["偷月亮的人","靜止的人","藍色的人","霧氣騰騰的人","踩影子的人"]},
  {"id":"feiteng","name":"沸騰跨世紀","file":"6人/沸騰跨世紀.html","players":6,"playersLabel":"3男3女","time":4,"timeLabel":"4小時","difficulty":0,"types":["歡樂","新手","機制","懷舊","團建","無兇手"],"theme":"happy","poster":"https://i.postimg.cc/fyw0htb3/IMG-7198.jpg","reviewKey":"沸騰跨世紀","characters":["包義峰","吳麗","劉洪濤","高巧燕","馬占山","張雲娟"]},
  {"id":"muxi","name":"木夕僧之戲","file":"7人/木夕僧之戲.html","players":7,"playersLabel":"4男3女","time":6,"timeLabel":"6小時","difficulty":5,"types":["日式","硬核","變格","燒腦","機制","推理"],"theme":"horror","poster":"https://i.postimg.cc/5twZZZz7/11dacc07-b497-4e5a-9862-9d7cfd0cc80e-S.png","reviewKey":"木夕僧之戲","characters":["月讀千鶴","般若彌生","不破秋波","天照櫻和","明智春光","大塚敬公","安倍偵探"]},
  {"id":"qunxing","name":"群星","file":"6人/群星.html","players":6,"playersLabel":"3男3女","time":5,"timeLabel":"5小時","difficulty":2,"types":["機制","情感","沉浸","太空","新手"],"theme":"space","poster":"https://i.postimg.cc/G3DGXBM5/image.jpg","reviewKey":"群星","characters":["張北斗","達莉婭","索菲亞","貝斯","馬斯克","伊萬"]},
  {"id":"anjian","name":"案件重演","file":"7人/案件重演.html","players":7,"playersLabel":"4男3女","time":4.5,"timeLabel":"4.5小時","difficulty":3,"types":["科技","演繹","推理","機制","歡樂","還原"],"theme":"modern","poster":"https://i.postimg.cc/gJJH0V1F/image.jpg","reviewKey":"案件重演","characters":["劉天宇","梁　良","白　鷺","霍長生","唐　琪","謝思妍","盧　峰"]},
  {"id":"fengzi2","name":"瘋子2：我將在18歲後分裂成很多人","file":"6人/瘋子2.html","players":6,"playersLabel":"3男3女","time":6,"timeLabel":"6小時","difficulty":5,"types":["日式推理","變格","硬核","進階","微恐怖","繁體"],"theme":"horror","poster":"https://i.postimg.cc/W3dHNnnx/image.jpg","reviewKey":"瘋子2","characters":["大蛇","鋼筆","櫻","兔子","可樂","夫人"]},
  {"id":"fengqiu","name":"瘋囚於妄念之終","file":"6人/瘋囚於妄念之終.html","players":6,"playersLabel":"3男3女","time":5,"timeLabel":"5小時","difficulty":4,"types":["古風","驚悚","變格","進階","還原"],"theme":"horror","poster":"https://i.postimg.cc/YqYXV9qH/1742108932-138599662-g-l.jpg","reviewKey":"瘋囚於妄念之終","characters":["烏顏","唐小冉","宋清秋","沈煥","鄭學林","顧青杉"]},
  {"id":"chunbai","name":"純白少年的慢性死亡","file":"7人/純白少年的慢性死亡.html","players":7,"playersLabel":"3男4女","time":4.5,"timeLabel":"4.5小時","difficulty":0,"types":["懸疑","病態","還原","歡樂","荒誕","新手","無兇手"],"theme":"modern","poster":"https://i.postimg.cc/gjX9pHjJ/image.jpg","reviewKey":"純白少年的慢性死亡","characters":["紅色","橙色","黃色","綠色","青色","藍色","紫色"]},
  {"id":"chaiqian","name":"拆遷","file":"8人以上/拆遷.html","players":10,"playersLabel":"5男5女（可反串）","time":4,"timeLabel":"4小時","difficulty":1,"types":["陣營","機制","歡樂","現代","撕逼","新手"],"theme":"modern","poster":"https://i.postimg.cc/KcVXYpTR/image.jpg","reviewKey":"拆遷","characters":["劉米飯","周廣播","孫小美","張論文","林軟軟","王大炮","鄭老蔫","鄭高考","宋美容","趙尖果"]},
  {"id":"mianmeng","name":"眠夢不老泉","file":"6人/眠夢不老泉.html","players":6,"playersLabel":"3男3女","time":4.5,"timeLabel":"4.5小時","difficulty":2,"types":["情感","日式","沉浸","還原","新手"],"theme":"shrine","poster":"https://i.postimg.cc/DwD8FHhJ/2025-09-03-102020.png","reviewKey":"眠夢不老泉","characters":["阿杉","邦迪","伊伊","達文西","蜜兒","小喬"]},
  {"id":"nianlun","name":"年輪","file":"5人/年輪.html","players":5,"playersLabel":"3男2女","time":5,"timeLabel":"5小時","difficulty":5,"types":["硬核","推理","燒腦","變格","現代"],"theme":"mystery","poster":"https://i.postimg.cc/L8XcWh1Q/109951165590072847.jpg","reviewKey":"年輪","characters":["劉伯釗","陳爍","姚波","袁本","王小冉"]},
  {"id":"shenle","name":"神樂湯","file":"5人/神樂湯.html","players":5,"playersLabel":"3男2女","time":4.5,"timeLabel":"4-5小時","difficulty":4,"types":["日式","硬核","還原","推理","機制"],"theme":"shrine","poster":"https://i.postimg.cc/JzGNvW45/arch.jpg","reviewKey":"神樂湯","characters":["螃蟹","青蛙","黑魚","甲魚","豚豚"]},
  {"id":"chaiqian2","name":"拆遷2買房","file":"8人以上/拆遷2.html","players":10,"playersLabel":"5男5女（可反串）","time":4,"timeLabel":"4小時","difficulty":1,"types":["續集","機制","歡樂","陣營","現代","房產","博弈"],"theme":"modern","poster":"https://i.postimg.cc/85kxw6QF/v2-84e72c373c2077e6324e282bd93eba61-1440w.png","reviewKey":"拆遷2","characters":["董大爺","武貝勒","陳小民","陳大寶","賈倒騰","趙仲介","朱翡翠","劉小曼","周廣播","王二姐"]},
  {"id":"jiuda","name":"酒大奇蹟","file":"7人/酒大奇蹟.html","players":7,"playersLabel":"4男3女（可反串）","time":4.5,"timeLabel":"4-5小時","difficulty":3,"types":["歡樂","未來","機制","酒文化","科幻","特殊","沉浸"],"theme":"space","poster":"https://i.postimg.cc/1X7LT5c9/2025-08-28-123509.png","reviewKey":"酒大奇蹟","characters":["查理","羅婆婆","逆火","華生","周念","盧致標","鄧圓順"]},
  {"id":"qingjiang","name":"請將我深埋","file":"6人/請將我深埋.html","players":6,"playersLabel":"3男3女（可反串）","time":4.5,"timeLabel":"4-5小時","difficulty":4,"types":["日式","推理","還原","硬核","情感","懸疑","進階"],"theme":"modern","poster":"https://i.postimg.cc/wv0KPH3k/1-S-5.jpg","reviewKey":"請將我深埋","characters":["藤原子蛟","酒井藝","高木折浩","高海敏","森田木果","小野可可"]},
  {"id":"fengqi","name":"風起時想你","file":"6人/風起時想你.html","players":6,"playersLabel":"3男3女","time":4,"timeLabel":"4小時","difficulty":1,"types":["情感","現代","沉浸","愛情","新手"],"theme":"love","poster":"https://i.postimg.cc/XqvNPrvx/image.jpg","reviewKey":"風起時想你","characters":["林碩","陳煜","白榆","沈念","顧薇","楊若楠"]},
  {"id":"bingjiao3","name":"病嬌3：近乎正常的我們","file":"6人/病嬌3近乎正常的我們.html","players":6,"playersLabel":"3男3女","time":5,"timeLabel":"5小時","difficulty":4,"types":["微恐","還原","推理","沉浸","進階"],"theme":"horror","poster":"https://i.postimg.cc/Gpvg6BBj/image.jpg","reviewKey":"病嬌3近乎正常的我們","characters":["星期二","星期三","星期四","星期五","星期六","星期日"]},
  {"id":"tiancai","name":"天才在左我在右","file":"7人/天才在左我在右.html","players":7,"playersLabel":"7人（不限性別）","time":4.5,"timeLabel":"4-5小時","difficulty":3,"types":["現代","推理","本格","還原","硬核","微恐","繁體"],"theme":"mystery","poster":"https://i.postimg.cc/c4gk78LJ/image.png","reviewKey":"天才在左我在右","characters":["偽面者","獵心師","低語者","匿行者","築夢師","犧牲者","執刑者"]},
  {"id":"taiyang","name":"太陽可以是藍色嗎","file":"6人/太陽可以是藍色嗎.html","players":6,"playersLabel":"3男3女","time":4.5,"timeLabel":"4.5小時","difficulty":0,"types":["現代","情感","純愛","浪漫","無兇手"],"theme":"modern","poster":"https://i.postimg.cc/sXBRPWRV/image.jpg","reviewKey":"太陽可以是藍色嗎","characters":["清遙","步含光","胡蝶","余朝","池森","初見"]},
  {"id":"zuozuo","name":"左左","file":"6人/左左.html","players":6,"playersLabel":"3男3女（原版7人）","time":5,"timeLabel":"約5小時","difficulty":4,"types":["現代","驚悚","還原","獵奇","沉浸","微恐","繁體","城限"],"theme":"horror","poster":"https://i.postimg.cc/d1ysfhyh/212x300.jpg","reviewKey":"左左","characters":["角色一","角色二","角色三","角色四","角色五","角色六"]},
  {"id":"changchun","name":"常春藤公寓","file":"6人/常春藤公寓.html","players":6,"playersLabel":"4男2女（可反串）","time":4,"timeLabel":"4小時","difficulty":3,"types":["本格","推理","還原","微恐","現代","架空","新手友善","繁化"],"theme":"mystery","poster":"https://i.postimg.cc/7hgnYWvJ/image.jpg","reviewKey":"常春藤公寓","characters":["星期一","星期二","星期四","星期五","星期六","星期天"]},
  {"id":"45","name":"45","file":"6人/45.html","players":6,"playersLabel":"4男2女（可反串）","time":4,"timeLabel":"4小時","difficulty":4,"types":["推理","本格","現代","微恐","還原","新手友善","進階可玩","繁化"],"theme":"mystery","poster":"https://i.postimg.cc/yYJhpxpr/gto1-Zyy-LPx-DJj-X-KTw-YLkw-Rfk-HCgw2-Dmff-Uk6-Iuh-DMk92fa-X8g0k5ub-Yf-Wa-N-I9-A.jpg","reviewKey":"45","characters":["李瀚明","林明","秦蒼","秦花語","楊星彩","張耀雲"]},
  {"id":"shanglu","name":"上路","file":"5人/上路.html","players":5,"playersLabel":"2男3女","time":4,"timeLabel":"4小時","difficulty":4,"types":["現代","恐怖","硬核","還原","變格","進階","繁體"],"theme":"horror","poster":"https://i.postimg.cc/L5CwvkVd/image.jpg","reviewKey":"上路","characters":["達澤明","張雅文","張卓君","阿花","達雯菁"]},
  {"id":"nihao","name":"你好","file":"6人/你好.html","players":6,"playersLabel":"3男3女","time":3.5,"timeLabel":"3-4小時","difficulty":1,"types":["現代","情感","沉浸","治癒","還原","本格"],"theme":"love","poster":"https://i.postimg.cc/yYHRnqbT/1756965231384-2b83cb44-9f84-4eda-b1a5-1eeeedac38fb-2.jpg","reviewKey":"你好","characters":["李海澤","阿瑤","夏雲峥","于婉兒","梁梓奕","林墨"]},
  {"id":"nanjing","name":"諜影南京風沙","file":"8人以上/南京風沙.html","players":8,"playersLabel":"5男3女","time":5,"timeLabel":"5小時","difficulty":4,"types":["民國","陣營","諜戰","還原","本格"],"theme":"history","poster":"https://i.postimg.cc/FHhLrJhf/page-0001.jpg","reviewKey":"南京風沙","characters":["安軍","鄧萍萍","歐陽澤","秦晴","羅文和","劉宗錫","周毅剛","杜安嵐"]},
  {"id":"gaoqian","name":"搞錢","file":"8人以上/搞錢.html","players":10,"playersLabel":"7-10人（可反串）","time":4.5,"timeLabel":"4-5小時","difficulty":1,"types":["歡樂","機制","陣營","現代","商戰"],"theme":"happy","poster":"https://i.postimg.cc/Bb2bW6Xn/4x5.png","reviewKey":"搞錢","characters":["林笑","趙行遠","董建國","白如鏡","藤原凌","瑟琳娜","齊梅","鄭義","李民俊","賈仁君"]},
  {"id":"beiji","name":"放棄生活去北極","file":"6人/放棄生活去北極.html","players":6,"playersLabel":"3男3女","time":4,"timeLabel":"4小時","difficulty":0,"types":["日式","情感","立意","治癒","新手","機制","歡樂","沉浸"],"theme":"shrine","poster":"https://i.postimg.cc/zvKbZd9Y/20211010172344555-0134.jpg","reviewKey":"放棄生活去北極","characters":["木木警官","娘口三三","佐藤","3.14159","絕緣體","方向盤"]},
  {"id":"sizhe","name":"死者在幻夜中醒來","file":"7人/死者在幻夜中醒來.html","players":7,"playersLabel":"3男3女+1","time":7,"timeLabel":"7小時","difficulty":5,"types":["日式","硬核","推理","還原","詭計","燒腦","進階"],"theme":"mystery","poster":"https://i.postimg.cc/LsZ4L32C/image-2-730x1024.png","reviewKey":"死者在幻夜中醒來","characters":["戴著面具的人","青年女人","臉上帶痣的中年女人","年輕男人","小男孩","長髮中年女子","中年男人"]},
  {"id":"hezi","name":"盒子先生的秘密商店","file":"7人/盒子先生的秘密商店.html","players":7,"playersLabel":"4男3女","time":4,"timeLabel":"4小時","difficulty":4,"types":["現代","驚悚","還原","硬核","獵奇","心理","進階"],"theme":"horror","poster":"https://i.postimg.cc/hvs5q3Hj/f7cd87b7-8042-4163-b01c-12a159617662-S-Mr-Boxs-Secret-Store.png","reviewKey":"盒子先生的秘密商店","characters":["BE大師","主角光環","正常人類","江郎才盡","童年味道","逆旅人生","靈魂畫手"]},
  {"id":"chongqing","name":"諜影重慶迷霧","file":"8人以上/重慶迷霧.html","players":8,"playersLabel":"6男2女","time":5,"timeLabel":"5小時","difficulty":5,"types":["諜戰","硬核","推理","還原","陣營","本格"],"theme":"mystery","poster":"https://i.postimg.cc/DyZDgnDN/2025-09-05-154322.png","reviewKey":"重慶迷霧","characters":["張敬佑","秦詩琪","余笑笑","文國俊","黎旭","左鋒","王志華","曾強"]},
  {"id":"wuya","name":"霧鴉館","file":"6人/霧鴉館.html","players":6,"playersLabel":"4男2女","time":5.5,"timeLabel":"5-6小時","difficulty":4,"types":["現代","架空","恐怖","硬核","密室","變格"],"theme":"horror","poster":"https://i.postimg.cc/wB5wB5ZX/1-S.jpg","reviewKey":"霧鴉館","characters":["陽光帥氣男生","綁著繃帶男子","黑瘦中年男人","儒雅眼鏡男子","幹練短髮女人","微胖婦女"]},
  {"id":"fengzhong","name":"風中有朵雨做的雲","file":"5人/風中有朵雨做的雲.html","players":5,"playersLabel":"3男2女","time":4,"timeLabel":"4小時","difficulty":3,"types":["港風","迪廳","微恐","情感","推理","沉浸"],"theme":"modern","poster":"https://i.postimg.cc/L57VYGP5/IMG-7151.jpg","reviewKey":"風中有朵雨做的雲","characters":["陳韻","劉飛宇","張龍","蘇金巧","李曉峯"]},
  {"id":"jingyu","name":"鯨魚馬戲團","file":"6人/鯨魚馬戲團.html","players":6,"playersLabel":"2男4女","time":3.5,"timeLabel":"3-4小時","difficulty":2,"types":["情感","溫情","新手","還原"],"theme":"space","poster":"https://i.postimg.cc/ZKPLFj52/369-E2-FA6-448-B-4-C9-A-8-A6-E-8-B077276577-B.jpg","reviewKey":"鯨魚馬戲團","characters":["雲雲","天天","圓圓","萱萱","飛飛","落落"]},
  {"id":"wuhuang","name":"吾皇在上","file":"8人以上/吾皇在上.html","players":8,"playersLabel":"8-9人","time":4,"timeLabel":"4小時","difficulty":3,"types":["宮鬥","歡樂","推理","角色扮演","古風","陣營","機制","新手"],"theme":"ancient","poster":"https://i.postimg.cc/W1T17C8Z/feng-mian1-page-0001.jpg","reviewKey":"吾皇在上","characters":["李諳","金統領","林老公公","小卓子","劉貴妃","啡貴人","王貴人","侍女環兒","王太醫"]},
  {"id":"wodi","name":"臥底模擬訓練","file":"7人/臥底模擬訓練.html","players":7,"playersLabel":"7人不限","time":4,"timeLabel":"3.5-4小時","difficulty":4,"types":["硬核","推理","新手友善","警匪","現代"],"theme":"modern","poster":"https://i.postimg.cc/k4N07QBP/202404241547-031-orig.jpg","reviewKey":"臥底模擬訓練","characters":["候選人 A","候選人 B","候選人 C","候選人 D","候選人 E","候選人 F","候選人 G"]},
  {"id":"manhua","name":"漫畫裡的小黑人","file":"6人/漫畫裡的小黑人.html","players":6,"playersLabel":"6人","time":4.5,"timeLabel":"4-5小時","difficulty":3,"types":["歡樂","還原","童話","機制","新手友善"],"theme":"happy","poster":"https://i.postimg.cc/yNpptNdn/202304130041-059.jpg","reviewKey":"漫畫裡的小黑人","characters":["毛利小次郎","中華大當家","賽華陀","東門慶","洪興陳好難","芳心縱火犯"]},
  {"id":"xuexiang","name":"雪鄉連環殺人事件","file":"6人/雪鄉連環殺人事件.html","players":6,"playersLabel":"3男3女","time":4,"timeLabel":"4小時","difficulty":3,"types":["驚悚","微恐","演繹","推理","還原"],"theme":"horror","poster":"https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_1000,w_500,f_auto,q_auto/10858423/158745_191005.jpeg","reviewKey":"雪鄉連環殺人事件","characters":["陳吉","卓司元","崔鎧強","李開心","蕭萌","王琪"]},
  {"id":"naesxuwvx0","name":"那一束月光","file":"6人/那一束月光.html","players":6,"playersLabel":"3男3女","time":5,"timeLabel":"5小時","difficulty":1,"types":["現代","情感","歡樂","戀綜","無推理","新手友善"],"theme":"love","poster":"https://i.postimg.cc/SRQ7nsLC/hai-bao1.jpg","reviewKey":"那一束月光","characters":["姜安心","宋一嶼","吳倩尹","顧諾","林沐陽","許知言"]},
  {"id":"lxe8","name":"龍宴","file":"8人以上/龍宴.html","players":8,"playersLabel":"5男3女","time":5,"timeLabel":"5小時","difficulty":3,"types":["古裝","宮廷","推理","陣營","機制"],"theme":"horror","poster":"https://i.postimg.cc/4dxTwvXZ/SKM-C30820072713280-0001.jpg","reviewKey":"龍宴","characters":["宋婷","林婉兒","陳曦","韓淳","李清文","陳敬之","韓忠","趙衛"]},
  {"id":"fengtuz","name":"瘋兔子，白又白，砍下腦袋飛起來","file":"6人/瘋兔子白又白砍下腦袋飛起來.html","players":6,"playersLabel":"3男3女（可反串）","time":4.5,"timeLabel":"4.5小時","difficulty":2,"types":["架空","還原","驚悚","怪談","新手"],"theme":"horror","poster":"劇本資料/角色海報/《疯兔子》—主海报.jpg","reviewKey":"瘋兔子，白又白，砍下腦袋飛起來","characters":["夏瞳","簡菲菲","姜沁","簡辭","林雲書","王之喻"]},
  {"id":"chunzhou","name":"春晝短","file":"6人/春晝短.html","players":6,"playersLabel":"3男3女","time":4,"timeLabel":"4小時","difficulty":3,"types":["現代","情感","沉浸","治癒","進階"],"theme":"love","poster":"https://i.postimg.cc/XqQBwLYR/ju-ben-hai-bao1.jpg","reviewKey":"春晝短","characters":["何西西","喬齊","楊夢詩","林宇白","余想","陳鏡"]},
  {"id":"jinmen","name":"津門遺雲","file":"7人/津門遺雲.html","players":7,"playersLabel":"4男3女","time":4.5,"timeLabel":"4-5小時","difficulty":2,"types":["民國","歡樂","嘴砲","陣營","新手"],"theme":"history","poster":"https://i.postimg.cc/x8yfpDz9/feng-mian2.png","reviewKey":"津門遺雲","characters":["大少爺","大少奶奶","二少爺","二少奶奶","三小姐","四少爺","大掌櫃"]},
  {"id":"jimu2","name":"極目2：九爺！我想給您養老","file":"7人/極目2九爺我想給您養老.html","players":7,"playersLabel":"4男3女","time":4.5,"timeLabel":"4-5小時","difficulty":3,"types":["民國","歡樂","陣營","機制","本格"],"theme":"history","poster":"https://i0.wp.com/www.larpinghk.com/wp-content/uploads/2024/12/%E5%88%B0%E5%BA%97%E6%B5%B7%E6%8A%A5.jpg?w=750&ssl=1","reviewKey":"極目2：九爺！我想給您養老","characters":["周謙","陳嘉樹","季修遠","陸秉白","商羽","李婉序","沈識月"]}
];

// scripts.js 會在首頁 DOM 完成後載入；立刻同步初始數量。
(function syncInitialScriptCount() {
  const countElement = document.getElementById('filteredCount');
  if (countElement) countElement.textContent = String(window.SCRIPTS.length);
})();
