/* ==========================================================
   劇本資料 · 單一資料來源（Single Source of Truth）
   新增 / 修改劇本只需改這裡一處。
   index.html 與 榮譽牆.html 皆讀取 window.SCRIPTS。
   欄位：id 名稱 file 路徑 / players 人數(數字,篩選用)
        playersLabel 人數顯示 / time 時長(數字,排序用) timeLabel 顯示
        difficulty 難度 0-5 / types 標籤 / theme 主題色
        poster 海報URL / reviewKey 榮譽牆評價對應鍵(CSV「劇本」欄)
   ========================================================== */
window.SCRIPTS = [
  {"id":"wangzuo","name":"王座","file":"7人/王座.html","players":7,"playersLabel":"4男3女","time":4.5,"timeLabel":"4.5小時","difficulty":2,"types":["神話","陣營","機制","新手","身份轉換"],"theme":"mytho","poster":"https://i.postimg.cc/d0cKpGxL/2021-11-13-195627.jpg","reviewKey":"王座"},
  {"id":"beiguo","name":"北國之春","file":"6人/北國之春.html","players":6,"playersLabel":"3男3女","time":4,"timeLabel":"4小時","difficulty":3,"types":["歡樂","推理","新手","情感"],"theme":"history","poster":"https://i.postimg.cc/yNWMsNFR/01.jpg","reviewKey":"北國之春"},
  {"id":"bielai","name":"別來無恙","file":"6人/別來無恙.html","players":6,"playersLabel":"3男3女","time":4,"timeLabel":"4小時","difficulty":1,"types":["情感","現代","新手","愛情","校園","遺憾"],"theme":"love","poster":"https://i.postimg.cc/ZR8GbTTx/image.jpg","reviewKey":"別來無恙"},
  {"id":"fengtian","name":"奉天1928","file":"5人/奉天1928.html","players":5,"playersLabel":"3男2女","time":4,"timeLabel":"4小時","difficulty":3,"types":["情感","民國","軍閥","家國","沉浸"],"theme":"history","poster":"https://i.postimg.cc/W3Z7nM68/image.jpg","reviewKey":"奉天1928"},
  {"id":"gucheng","name":"孤城","file":"7人/孤城.html","players":7,"playersLabel":"4男3女","time":4.5,"timeLabel":"4.5小時","difficulty":2,"types":["陣營","機制","情感","民國","諜戰"],"theme":"desert","poster":"https://i.postimg.cc/cCsdmcGG/b644a7b3-c9a4-4d08-b36d-c69cc70a0b39-S.png","reviewKey":"孤城"},
  {"id":"bingjiao","name":"病嬌男孩的精分日記","file":"7人/病嬌男孩的精分日記.html","players":7,"playersLabel":"7人不限","time":4.5,"timeLabel":"4-5小時","difficulty":4,"types":["微恐","還原","推理","沉浸"],"theme":"horror","poster":"https://i.postimg.cc/RZYbc6pZ/1.jpg","reviewKey":"病嬌男孩的精分日記"},
  {"id":"yinyuan","name":"陰緣","file":"6人/陰緣.html","players":6,"playersLabel":"3男3女","time":4,"timeLabel":"4小時","difficulty":2,"types":["古風","情感","恐怖","沉浸","雙主持"],"theme":"ancient","poster":"https://i.postimg.cc/qqp3BtDL/image.jpg","reviewKey":"陰緣"},
  {"id":"qingtian","name":"晴天神社","file":"6人/晴天神社.html","players":6,"playersLabel":"4男2女","time":4,"timeLabel":"4小時","difficulty":0,"types":["情感","日式","沉浸","還原","無兇手","新手"],"theme":"shrine","poster":"https://i.postimg.cc/QMd81msL/image.png","reviewKey":"晴天神社"},
  {"id":"lichuan","name":"漓川怪談簿","file":"7人/漓川怪談簿.html","players":7,"playersLabel":"3男4女","time":4.5,"timeLabel":"4.5小時","difficulty":4,"types":["日式","硬核推理","精怪","密室","進階","還原"],"theme":"mystery","poster":"https://i.postimg.cc/KvyQtdnC/海報.jpg","reviewKey":"漓川怪談簿"},
  {"id":"nairao","name":"誰動了我的奶酪","file":"6人/誰動了我的奶酪.html","players":6,"playersLabel":"2男4女","time":4,"timeLabel":"4小時","difficulty":3,"types":["歡樂","新手","童話","推理","輕鬆"],"theme":"happy","poster":"https://i.postimg.cc/hjP711CF/image.jpg","reviewKey":"誰動了我的奶酪"},
  {"id":"kuaile","name":"賣快樂的人","file":"5人/賣快樂的人.html","players":5,"playersLabel":"2男3女","time":5,"timeLabel":"5小時","difficulty":1,"types":["情感","新手","沉浸","立意","日式","現代","無兇手"],"theme":"modern","poster":"https://i.postimg.cc/8zDnCPgc/image.jpg","reviewKey":"賣快樂的人"},
  {"id":"feiteng","name":"沸騰跨世紀","file":"6人/沸騰跨世紀.html","players":6,"playersLabel":"3男3女","time":4,"timeLabel":"4小時","difficulty":0,"types":["歡樂","新手","機制","懷舊","團建","無兇手"],"theme":"happy","poster":"https://i.postimg.cc/fyw0htb3/IMG-7198.jpg","reviewKey":"沸騰跨世紀"},
  {"id":"muxi","name":"木夕僧之戲","file":"7人/木夕僧之戲.html","players":7,"playersLabel":"4男3女","time":6,"timeLabel":"6小時","difficulty":5,"types":["日式","硬核","變格","燒腦","機制","推理"],"theme":"horror","poster":"https://i.postimg.cc/5twZZZz7/11dacc07-b497-4e5a-9862-9d7cfd0cc80e-S.png","reviewKey":"木夕僧之戲"},
  {"id":"qunxing","name":"群星","file":"6人/群星.html","players":6,"playersLabel":"3男3女","time":5,"timeLabel":"5小時","difficulty":2,"types":["機制","情感","沉浸","太空","新手"],"theme":"space","poster":"https://i.postimg.cc/G3DGXBM5/image.jpg","reviewKey":"群星"},
  {"id":"anjian","name":"案件重演","file":"7人/案件重演.html","players":7,"playersLabel":"4男3女","time":4.5,"timeLabel":"4.5小時","difficulty":3,"types":["科技","演繹","推理","機制","歡樂","還原"],"theme":"modern","poster":"https://i.postimg.cc/gJJH0V1F/image.jpg","reviewKey":"案件重演"},
  {"id":"fengzi2","name":"瘋子2：我將在18歲後分裂成很多人","file":"6人/瘋子2.html","players":6,"playersLabel":"3男3女","time":6,"timeLabel":"6小時","difficulty":5,"types":["日式推理","變格","硬核","進階","微恐怖","繁體"],"theme":"horror","poster":"https://i.postimg.cc/W3dHNnnx/image.jpg","reviewKey":"瘋子2"},
  {"id":"fengqiu","name":"瘋囚於妄念之終","file":"6人/瘋囚於妄念之終.html","players":6,"playersLabel":"3男3女","time":5,"timeLabel":"5小時","difficulty":4,"types":["古風","驚悚","變格","進階","還原"],"theme":"horror","poster":"https://i.postimg.cc/YqYXV9qH/1742108932-138599662-g-l.jpg","reviewKey":"瘋囚於妄念之終"},
  {"id":"chunbai","name":"純白少年的慢性死亡","file":"7人/純白少年的慢性死亡.html","players":7,"playersLabel":"3男4女","time":4.5,"timeLabel":"4.5小時","difficulty":0,"types":["懸疑","病態","還原","歡樂","荒誕","新手","無兇手"],"theme":"modern","poster":"https://i.postimg.cc/gjX9pHjJ/image.jpg","reviewKey":"純白少年的慢性死亡"},
  {"id":"chaiqian","name":"拆遷","file":"8人以上/拆遷.html","players":10,"playersLabel":"5男5女（可反串）","time":4,"timeLabel":"4小時","difficulty":1,"types":["陣營","機制","歡樂","現代","撕逼","新手"],"theme":"modern","poster":"https://i.postimg.cc/KcVXYpTR/image.jpg","reviewKey":"拆遷"},
  {"id":"mianmeng","name":"眠夢不老泉","file":"6人/眠夢不老泉.html","players":6,"playersLabel":"3男3女","time":4.5,"timeLabel":"4.5小時","difficulty":2,"types":["情感","日式","沉浸","還原","新手"],"theme":"shrine","poster":"https://i.postimg.cc/DwD8FHhJ/2025-09-03-102020.png","reviewKey":"眠夢不老泉"},
  {"id":"nianlun","name":"年輪","file":"5人/年輪.html","players":5,"playersLabel":"3男2女","time":5,"timeLabel":"5小時","difficulty":5,"types":["硬核","推理","燒腦","變格","現代"],"theme":"mystery","poster":"https://i.postimg.cc/L8XcWh1Q/109951165590072847.jpg","reviewKey":"年輪"},
  {"id":"shenle","name":"神樂湯","file":"5人/神樂湯.html","players":5,"playersLabel":"3男2女","time":4.5,"timeLabel":"4-5小時","difficulty":4,"types":["日式","硬核","還原","推理","機制"],"theme":"shrine","poster":"https://i.postimg.cc/JzGNvW45/arch.jpg","reviewKey":"神樂湯"},
  {"id":"chaiqian2","name":"拆遷2買房","file":"8人以上/拆遷2.html","players":10,"playersLabel":"5男5女（可反串）","time":4,"timeLabel":"4小時","difficulty":1,"types":["續集","機制","歡樂","陣營","現代","房產","博弈"],"theme":"modern","poster":"https://i.postimg.cc/85kxw6QF/v2-84e72c373c2077e6324e282bd93eba61-1440w.png","reviewKey":"拆遷2"},
  {"id":"jiuda","name":"酒大奇蹟","file":"7人/酒大奇蹟.html","players":7,"playersLabel":"4男3女（可反串）","time":4.5,"timeLabel":"4-5小時","difficulty":3,"types":["歡樂","未來","機制","酒文化","科幻","特殊","沉浸"],"theme":"space","poster":"https://i.postimg.cc/1X7LT5c9/2025-08-28-123509.png","reviewKey":"酒大奇蹟"},
  {"id":"qingjiang","name":"請將我深埋","file":"6人/請將我深埋.html","players":6,"playersLabel":"3男3女（可反串）","time":4.5,"timeLabel":"4-5小時","difficulty":4,"types":["日式","推理","還原","硬核","情感","懸疑","進階"],"theme":"modern","poster":"https://i.postimg.cc/wv0KPH3k/1-S-5.jpg","reviewKey":"請將我深埋"},
  {"id":"fengqi","name":"風起時想你","file":"6人/風起時想你.html","players":6,"playersLabel":"3男3女","time":4,"timeLabel":"4小時","difficulty":1,"types":["情感","現代","沉浸","愛情","新手"],"theme":"love","poster":"https://i.postimg.cc/XqvNPrvx/image.jpg","reviewKey":"風起時想你"},
  {"id":"bingjiao3","name":"病嬌3：近乎正常的我們","file":"6人/病嬌3近乎正常的我們.html","players":6,"playersLabel":"3男3女","time":5,"timeLabel":"5小時","difficulty":4,"types":["微恐","還原","推理","沉浸","進階"],"theme":"horror","poster":"https://i.postimg.cc/Gpvg6BBj/image.jpg","reviewKey":"病嬌3近乎正常的我們"},
  {"id":"tiancai","name":"天才在左我在右","file":"7人/天才在左我在右.html","players":7,"playersLabel":"7人（不限性別）","time":4.5,"timeLabel":"4-5小時","difficulty":3,"types":["現代","推理","本格","還原","硬核","微恐","繁體"],"theme":"mystery","poster":"https://i.postimg.cc/c4gk78LJ/image.png","reviewKey":"天才在左我在右"},
  {"id":"taiyang","name":"太陽可以是藍色嗎","file":"6人/太陽可以是藍色嗎.html","players":6,"playersLabel":"3男3女","time":4.5,"timeLabel":"4.5小時","difficulty":0,"types":["現代","情感","純愛","浪漫","無兇手"],"theme":"modern","poster":"https://i.postimg.cc/sXBRPWRV/image.jpg","reviewKey":"太陽可以是藍色嗎"},
  {"id":"zuozuo","name":"左左","file":"6人/左左.html","players":6,"playersLabel":"3男3女（原版7人）","time":5,"timeLabel":"約5小時","difficulty":4,"types":["現代","驚悚","還原","獵奇","沉浸","微恐","繁體","城限"],"theme":"horror","poster":"https://i.postimg.cc/d1ysfhyh/212x300.jpg","reviewKey":"左左"},
  {"id":"changchun","name":"常春藤公寓","file":"6人/常春藤公寓.html","players":6,"playersLabel":"4男2女（可反串）","time":4,"timeLabel":"4小時","difficulty":3,"types":["本格","推理","還原","微恐","現代","架空","新手友善","繁化"],"theme":"mystery","poster":"https://i.postimg.cc/7hgnYWvJ/image.jpg","reviewKey":"常春藤公寓"},
  {"id":"45","name":"45","file":"6人/45.html","players":6,"playersLabel":"4男2女（可反串）","time":4,"timeLabel":"4小時","difficulty":4,"types":["推理","本格","現代","微恐","還原","新手友善","進階可玩","繁化"],"theme":"mystery","poster":"https://i.postimg.cc/yYJhpxpr/gto1-Zyy-LPx-DJj-X-KTw-YLkw-Rfk-HCgw2-Dmff-Uk6-Iuh-DMk92fa-X8g0k5ub-Yf-Wa-N-I9-A.jpg","reviewKey":"45"},
  {"id":"shanglu","name":"上路","file":"5人/上路.html","players":5,"playersLabel":"2男3女","time":4,"timeLabel":"4小時","difficulty":4,"types":["現代","恐怖","硬核","還原","變格","進階","繁體"],"theme":"horror","poster":"https://i.postimg.cc/L5CwvkVd/image.jpg","reviewKey":"上路"},
  {"id":"nihao","name":"你好","file":"6人/你好.html","players":6,"playersLabel":"3男3女","time":3.5,"timeLabel":"3-4小時","difficulty":1,"types":["現代","情感","沉浸","治癒","還原","本格"],"theme":"love","poster":"https://i.postimg.cc/yYHRnqbT/1756965231384-2b83cb44-9f84-4eda-b1a5-1eeeedac38fb-2.jpg","reviewKey":"你好"},
  {"id":"nanjing","name":"諜影南京風沙","file":"8人以上/南京風沙.html","players":8,"playersLabel":"5男3女","time":5,"timeLabel":"5小時","difficulty":4,"types":["民國","陣營","諜戰","還原","本格"],"theme":"history","poster":"https://i.postimg.cc/FHhLrJhf/page-0001.jpg","reviewKey":"南京風沙"},
  {"id":"gaoqian","name":"搞錢","file":"8人以上/搞錢.html","players":10,"playersLabel":"7-10人（可反串）","time":4.5,"timeLabel":"4-5小時","difficulty":1,"types":["歡樂","機制","陣營","現代","商戰"],"theme":"happy","poster":"https://i.postimg.cc/Bb2bW6Xn/4x5.png","reviewKey":"搞錢"},
  {"id":"beiji","name":"放棄生活去北極","file":"6人/放棄生活去北極.html","players":6,"playersLabel":"3男3女","time":4,"timeLabel":"4小時","difficulty":0,"types":["日式","情感","立意","治癒","新手","機制","歡樂","沉浸"],"theme":"shrine","poster":"https://i.postimg.cc/zvKbZd9Y/20211010172344555-0134.jpg","reviewKey":"放棄生活去北極"},
  {"id":"sizhe","name":"死者在幻夜中醒來","file":"7人/死者在幻夜中醒來.html","players":7,"playersLabel":"3男3女+1","time":7,"timeLabel":"7小時","difficulty":5,"types":["日式","硬核","推理","還原","詭計","燒腦","進階"],"theme":"mystery","poster":"https://i.postimg.cc/LsZ4L32C/image-2-730x1024.png","reviewKey":"死者在幻夜中醒來"},
  {"id":"hezi","name":"盒子先生的秘密商店","file":"7人/盒子先生的秘密商店.html","players":7,"playersLabel":"4男3女","time":4,"timeLabel":"4小時","difficulty":4,"types":["現代","驚悚","還原","硬核","獵奇","心理","進階"],"theme":"horror","poster":"https://i.postimg.cc/hvs5q3Hj/f7cd87b7-8042-4163-b01c-12a159617662-S-Mr-Boxs-Secret-Store.png","reviewKey":"盒子先生的秘密商店"},
  {"id":"chongqing","name":"諜影重慶迷霧","file":"8人以上/重慶迷霧.html","players":8,"playersLabel":"6男2女","time":5,"timeLabel":"5小時","difficulty":5,"types":["諜戰","硬核","推理","還原","陣營","本格"],"theme":"mystery","poster":"https://i.postimg.cc/DyZDgnDN/2025-09-05-154322.png","reviewKey":"重慶迷霧"},
  {"id":"wuya","name":"霧鴉館","file":"6人/霧鴉館.html","players":6,"playersLabel":"4男2女","time":5.5,"timeLabel":"5-6小時","difficulty":4,"types":["現代","架空","恐怖","硬核","密室","變格"],"theme":"horror","poster":"https://i.postimg.cc/wB5wB5ZX/1-S.jpg","reviewKey":"霧鴉館"},
  {"id":"fengzhong","name":"風中有朵雨做的雲","file":"5人/風中有朵雨做的雲.html","players":5,"playersLabel":"3男2女","time":4,"timeLabel":"4小時","difficulty":3,"types":["港風","迪廳","微恐","情感","推理","沉浸"],"theme":"modern","poster":"https://i.postimg.cc/L57VYGP5/IMG-7151.jpg","reviewKey":"風中有朵雨做的雲"},
  {"id":"jingyu","name":"鯨魚馬戲團","file":"6人/鯨魚馬戲團.html","players":6,"playersLabel":"2男4女","time":3.5,"timeLabel":"3-4小時","difficulty":2,"types":["情感","溫情","新手","還原"],"theme":"space","poster":"https://i.postimg.cc/ZKPLFj52/369-E2-FA6-448-B-4-C9-A-8-A6-E-8-B077276577-B.jpg","reviewKey":"鯨魚馬戲團"},
  {"id":"wuhuang","name":"吾皇在上","file":"8人以上/吾皇在上.html","players":8,"playersLabel":"8-9人","time":4,"timeLabel":"4小時","difficulty":3,"types":["宮鬥","歡樂","推理","角色扮演","古風","陣營","機制","新手"],"theme":"ancient","poster":"https://i.postimg.cc/W1T17C8Z/feng-mian1-page-0001.jpg","reviewKey":"吾皇在上"},
  {"id":"wodi","name":"臥底模擬訓練","file":"7人/臥底模擬訓練.html","players":7,"playersLabel":"7人不限","time":4,"timeLabel":"3.5-4小時","difficulty":4,"types":["硬核","推理","新手友善","警匪","現代"],"theme":"modern","poster":"https://i.postimg.cc/k4N07QBP/202404241547-031-orig.jpg","reviewKey":"臥底模擬訓練"},
  {"id":"manhua","name":"漫畫裡的小黑人","file":"6人/漫畫裡的小黑人.html","players":6,"playersLabel":"6人","time":4.5,"timeLabel":"4-5小時","difficulty":3,"types":["歡樂","還原","童話","機制","新手友善"],"theme":"happy","poster":"https://i.postimg.cc/yNpptNdn/202304130041-059.jpg","reviewKey":"漫畫裡的小黑人"},
  {"id":"xuexiang","name":"雪鄉連環殺人事件","file":"6人/雪鄉連環殺人事件.html","players":6,"playersLabel":"3男3女","time":4,"timeLabel":"4小時","difficulty":3,"types":["驚悚","微恐","演繹","推理","還原"],"theme":"horror","poster":"https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_1000,w_500,f_auto,q_auto/10858423/158745_191005.jpeg","reviewKey":"雪鄉連環殺人事件"},
  {"id":"naesxuwvx0","name":"那一束月光","file":"6人/那一束月光.html","players":6,"playersLabel":"3男3女","time":5,"timeLabel":"5小時","difficulty":1,"types":["現代","情感","歡樂","戀綜","無推理","新手友善"],"theme":"love","poster":"https://i.postimg.cc/SRQ7nsLC/hai-bao1.jpg","reviewKey":"那一束月光"},
  {"id":"lxe8","name":"龍宴","file":"8人以上/龍宴.html","players":8,"playersLabel":"5男3女","time":5,"timeLabel":"5小時","difficulty":3,"types":["古裝","宮廷","推理","陣營","機制"],"theme":"horror","poster":"https://i.postimg.cc/4dxTwvXZ/SKM-C30820072713280-0001.jpg","reviewKey":"龍宴"},
  {"id":"fengtuz","name":"瘋兔子，白又白，砍下腦袋飛起來","file":"6人/瘋兔子白又白砍下腦袋飛起來.html","players":6,"playersLabel":"3男3女（可反串）","time":4.5,"timeLabel":"4.5小時","difficulty":2,"types":["架空","還原","驚悚","怪談","新手"],"theme":"horror","poster":"劇本資料/角色海報/《疯兔子》—主海报.jpg","reviewKey":"瘋兔子，白又白，砍下腦袋飛起來"},
  {"id":"chunzhou","name":"春昼短","file":"6人/春昼短.html","players":6,"playersLabel":"3男3女","time":4,"timeLabel":"4小時","difficulty":3,"types":["現代","情感","沉浸","治癒","進階"],"theme":"love","poster":"","reviewKey":"春昼短"},
  {"id":"jinmen","name":"津門遺雲","file":"8人以上/津門遺雲.html","players":8,"playersLabel":"4男3女＋捕快","time":4.5,"timeLabel":"4-5小時","difficulty":2,"types":["民國","歡樂","嘴砲","陣營","新手"],"theme":"history","poster":"","reviewKey":"津門遺雲"},
  {"id":"jimu2","name":"極目2：九爺！我想給您養老","file":"7人/極目2九爺我想給您養老.html","players":7,"playersLabel":"4男3女","time":4.5,"timeLabel":"4-5小時","difficulty":3,"types":["民國","歡樂","陣營","機制","本格"],"theme":"history","poster":"","reviewKey":"極目2：九爺！我想給您養老"}
];
